# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Hurb-iOS-Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  inhibit_all_warnings!
  use_frameworks!

  # Pods for Hurb-iOS-Challenge

  target 'Hurb-iOS-ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hurb-iOS-ChallengeUITests' do
    # Pods for testing
  end

end
