//
//  ProductDetailsViewController.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 19/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsDisplayLogic: AnyObject {
    
    func displaySomething(viewModel: ProductDetails.Something.ViewModel)
}

class ProductDetailsViewController: UIViewController {
    
    var interactor: ProductDetailsBusinessLogic?
    var router: (NSObjectProtocol & ProductDetailsRoutingLogic & ProductDetailsDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        super.prepare(for: segue, sender: sender)
        
    }
    
    // MARK: Do something
    
    func doSomething() {
        
        let request = ProductDetails.Something.Request()
        interactor?.doSomething(request: request)
    }
}

extension ProductDetailsViewController: ProductDetailsDisplayLogic {
    
    func displaySomething(viewModel: ProductDetails.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
