//
//  ProductDetailsConfigurator.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 19/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc class ProductDetailsConfigurator: NSObject {
    
    @objc static func setupArch(viewController: ProductDetailsViewController) {
        
        let presenter: ProductDetailsPresenter = ProductDetailsPresenter(viewController: viewController)
        let interactor: ProductDetailsInteractor = ProductDetailsInteractor(presenter: presenter, worker: ProductDetailsWorker())
        let router: ProductDetailsRouter = ProductDetailsRouter(viewController: viewController, dataStore: interactor)
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
