//
//  ProductDetailsPresenter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 19/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsPresentationLogic {
    
    func presentSomething(response: ProductDetails.Something.Response)
}

class ProductDetailsPresenter: ProductDetailsPresentationLogic {
    
    weak var viewController: ProductDetailsDisplayLogic?
    
    init(viewController: ProductDetailsDisplayLogic) {
        
        self.viewController = viewController
    }
    
    // MARK: Do something
    
    func presentSomething(response: ProductDetails.Something.Response) {
        
        let viewModel = ProductDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
