//
//  ProductDetailsModels.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 19/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetails {
    
    // MARK: Use cases
    
    enum Something {
        
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
