# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-hurb-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher', '~> 5.8'
  # Pods for desafio-hurb-ios

end
