# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTravel_iOS_Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'ImageSlideshow', '~> 1.9.0'
    pod "ImageSlideshow/Alamofire"
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'Alamofire'




  target 'iTravel_iOS_ChallengeTests' do
    inherit! :search_paths
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'ImageSlideshow', '~> 1.9.0'
    pod "ImageSlideshow/Alamofire"
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'Alamofire'

  end

  target 'iTravel_iOS_ChallengeUITests' do
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'ImageSlideshow', '~> 1.9.0'
    pod "ImageSlideshow/Alamofire"
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'Alamofire'


  end

end
