//
//  SearchLocationRouter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 17/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Private segues names
//private enum Segues: String {
//    case toSomewhere
//}

@objc protocol SearchLocationRoutingLogic {
    
    func routeTo(segue: UIStoryboardSegue, sender: Any?)
}

protocol SearchLocationDataPassing {
    
    var dataStore: SearchLocationDataStore? { get }
}

class SearchLocationRouter: NSObject, SearchLocationRoutingLogic, SearchLocationDataPassing {
    
    weak var viewController: SearchLocationViewController?
    var dataStore: SearchLocationDataStore?
    
    init(viewController: SearchLocationViewController, dataStore: SearchLocationDataStore) {
        
        self.viewController = viewController
        self.dataStore = dataStore
    }
    
    // MARK: Routing
    
    func routeTo(segue: UIStoryboardSegue, sender: Any?) {

//        switch segue.identifier {
//
//        case Segues.toSomewhere.rawValue:
//            if let nextController: SomewhereViewController = segue.destination as? SomewhereViewController {
//
//                SomewhereConfigurator.setupArch(viewController: nextController)
//            }
//            break
//
//        default:
//            break
//        }
    }
}
