//
//  SearchLocationPresenter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 17/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchLocationPresentationLogic {
    
    func presentLocations(response: SearchLocation.Setup.Response)
    func presentHideSkeleton()
    func presentErrorAlert()
}

class SearchLocationPresenter: SearchLocationPresentationLogic {
    
    weak var viewController: SearchLocationDisplayLogic?
    
    init(viewController: SearchLocationDisplayLogic) {
        
        self.viewController = viewController
    }
    
    // MARK: Do something
    
    func presentLocations(response: SearchLocation.Setup.Response) {
        
        let viewModel: SearchLocation.Setup.ViewModel = SearchLocation.Setup.ViewModel(locations: response.locations)
        self.viewController?.displayLocations(viewModel: viewModel)
    }
    
    func presentHideSkeleton() {
        
        self.viewController?.displayHideSkeleton()
    }
    
    func presentErrorAlert() {
        
        self.viewController?.displayErrorAlert()
    }
}
