# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Hurb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hurb
  pod 'lottie-ios'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ImageSlideshow'
  pod 'ImageSlideshow/SDWebImage'
  pod 'Firebase/Analytics'
  pod 'GoogleMaps'

  target 'HurbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HurbUITests' do
    inherit! :complete
    # Pods for testing
  end

end
