# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Challenge-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Challenge-ios
  pod 'Alamofire'
  pod 'Kingfisher'
  
end
