# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Challange HURB - Alpha' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Challange HURB - Alpha
  pod 'Moya', '~> 13.0'

  target 'Challange HURB - AlphaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Moya', '~> 13.0'
  end

  target 'Challange HURB - AlphaUITests' do
    # Pods for testing
    pod 'Moya', '~> 13.0'
  end

end
