//
//  SearchLocationViewController.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 17/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchLocationDisplayLogic: AnyObject {
    
    func displaySomething(viewModel: SearchLocation.Something.ViewModel)
}

class SearchLocationViewController: UIViewController {
    
    var interactor: SearchLocationBusinessLogic?
    var router: (NSObjectProtocol & SearchLocationRoutingLogic & SearchLocationDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        super.prepare(for: segue, sender: sender)
        
    }
    
    // MARK: Do something
    
    func doSomething() {
        
        let request = SearchLocation.Something.Request()
        interactor?.doSomething(request: request)
    }
}

extension SearchLocationViewController: SearchLocationDisplayLogic {
    
    func displaySomething(viewModel: SearchLocation.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
