//
//  SearchLocationWorker.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 17/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchLocationWorkerProtocol {
    
    func doSomeWork()
}

class SearchLocationWorker: SearchLocationWorkerProtocol {
    
    func doSomeWork() {
        
    }
}
