# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'HurbHotel_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HurbHotel_iOS
  pod 'Kingfisher'

end
