//
//  ProductsConfigurator.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 10/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc class ProductsConfigurator: NSObject {
    
    @objc static func setupArch(viewController: ProductsViewController) {
        
        let presenter: ProductsPresenter = ProductsPresenter(viewController: viewController)
        let interactor: ProductsInteractor = ProductsInteractor(presenter: presenter, worker: ProductsWorker())
        let router: ProductsRouter = ProductsRouter(viewController: viewController, dataStore: interactor)
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
