//
//  ProductsWorker.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 10/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import HUGraphQL

enum ServiceError: Error {
    
    case emptyReturn
    case unknown(_ message: String)
}

protocol ProductsWorkerProtocol {
    
    func searchProducts(term: String, page: Int, completion: @escaping (Result<[Product], ServiceError>) -> Void)
}

class ProductsWorker: ProductsWorkerProtocol {
    
    func searchProducts(term: String, page: Int, completion: @escaping (Result<[Product], ServiceError>) -> Void) {
        
        let pagination: HUGraphQL.SearchInputPagination = HUGraphQL.SearchInputPagination(page: page, limit: 50, sort: nil, sortOrder: nil)
        let query = HUGraphQL.SearchQuery(q: term, pagination: pagination)
        
        let graphQL = HUGService(enableLog: true)
        graphQL.client.fetch(query: query) { result in
            
            switch result {
                    
            case .success(let value):

                    if let listObject = value.data?.search?.results?.compactMap({ $0.resultMap }),
                       let jsonData = try? JSONSerialization.data(withJSONObject: listObject, options: .prettyPrinted),
                       let decoded = try? JSONDecoder().decode([Product].self, from: jsonData) {

                        completion(.success(decoded))

                    } else {
                        
                        completion(.failure(.emptyReturn))
                    }
                break
                    
            case .failure(let error):
                    completion(.failure(.unknown(error.localizedDescription)))
                    break
            }
        }
    }
}
