//
//  ProductsRouter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 10/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Private segues names
//private enum Segues: String {
//    case toSomewhere
//}

@objc protocol ProductsRoutingLogic {
    
    func routeTo(segue: UIStoryboardSegue, sender: Any?)
}

protocol ProductsDataPassing {
    
    var dataStore: ProductsDataStore? { get }
}

class ProductsRouter: NSObject, ProductsRoutingLogic, ProductsDataPassing {
    
    weak var viewController: ProductsViewController?
    var dataStore: ProductsDataStore?
    
    init(viewController: ProductsViewController, dataStore: ProductsDataStore) {
        
        self.viewController = viewController
        self.dataStore = dataStore
    }
    
    // MARK: Routing
    
    func routeTo(segue: UIStoryboardSegue, sender: Any?) {

//        switch segue.identifier {
//
//        case Segues.toSomewhere.rawValue:
//            if let nextController: SomewhereViewController = segue.destination as? SomewhereViewController {
//
//                SomewhereConfigurator.setupArch(viewController: nextController)
//            }
//            break
//
//        default:
//            break
//        }
    }
}
