//
//  ProductsPresenter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 10/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductsPresentationLogic {
    
    func presentSomething(response: Products.Something.Response)
}

class ProductsPresenter: ProductsPresentationLogic {
    
    weak var viewController: ProductsDisplayLogic?
    
    init(viewController: ProductsDisplayLogic) {
        
        self.viewController = viewController
    }
    
    // MARK: Do something
    
    func presentSomething(response: Products.Something.Response) {
        
        let viewModel = Products.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
