//
//  ProductsInteractor.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 10/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductsBusinessLogic {
    
    func doSomething(request: Products.Something.Request)
}

protocol ProductsDataStore {
    
    //var name: String { get set }
}

class ProductsInteractor: ProductsBusinessLogic, ProductsDataStore {
    
    var presenter: ProductsPresentationLogic?
    var worker: ProductsWorkerProtocol?
    //var name: String = ""
    
    init(presenter: ProductsPresentationLogic, worker: ProductsWorkerProtocol) {
        
        self.presenter = presenter
        self.worker = worker
    }
    
    // MARK: Do something
    
    func doSomething(request: Products.Something.Request) {

        let response = Products.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
