//
//  SearchProductModels.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 10/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchProduct {
    
    // MARK: Use cases
    
    enum Query {
        
        struct Request {
            
            var term: String
            var page: Int
            var limit: Int
        }
        
        struct Response {
            
            var pagination: Pagination
            var products: [Product]
        }
        
        struct ViewModel {
            
            var pagination: Pagination
            var products: [Product]
        }
    }
}
