//
//  HotelsConfigurator.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 05/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc class HotelsConfigurator: NSObject {
    
    @objc static func setupArch(viewController: HotelsViewController) {
        
        let presenter: HotelsPresenter = HotelsPresenter(viewController: viewController)
        let interactor: HotelsInteractor = HotelsInteractor(presenter: presenter, worker: HotelsWorker())
        let router: HotelsRouter = HotelsRouter(viewController: viewController, dataStore: interactor)
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
