//
//  HotelsInteractor.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 05/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HotelsBusinessLogic {
    
    func doSomething(request: Hotels.Something.Request)
}

protocol HotelsDataStore {
    
    //var name: String { get set }
}

class HotelsInteractor: HotelsBusinessLogic, HotelsDataStore {
    
    var presenter: HotelsPresentationLogic?
    var worker: HotelsWorkerProtocol?
    //var name: String = ""
    
    init(presenter: HotelsPresentationLogic, worker: HotelsWorkerProtocol) {
        
        self.presenter = presenter
        self.worker = worker
    }
    
    // MARK: Do something
    
    func doSomething(request: Hotels.Something.Request) {

        let response = Hotels.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
