//
//  HotelsRouter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 05/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Private segues names
//private enum Segues: String {
//    case toSomewhere
//}

@objc protocol HotelsRoutingLogic {
    
    func routeTo(segue: UIStoryboardSegue, sender: Any?)
}

protocol HotelsDataPassing {
    
    var dataStore: HotelsDataStore? { get }
}

class HotelsRouter: NSObject, HotelsRoutingLogic, HotelsDataPassing {
    
    weak var viewController: HotelsViewController?
    var dataStore: HotelsDataStore?
    
    init(viewController: HotelsViewController, dataStore: HotelsDataStore) {
        
        self.viewController = viewController
        self.dataStore = dataStore
    }
    
    // MARK: Routing
    
    func routeTo(segue: UIStoryboardSegue, sender: Any?) {

//        switch segue.identifier {
//
//        case Segues.toSomewhere.rawValue:
//            if let nextController: SomewhereViewController = segue.destination as? SomewhereViewController {
//
//                SomewhereConfigurator.setupArch(viewController: nextController)
//            }
//            break
//
//        default:
//            break
//        }
    }
}
