//
//  HotelsPresenter.swift
//  Hurb-iOS-Challenge
//
//  Created by Rômulo Monteiro on 05/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HotelsPresentationLogic {
    
    func presentSomething(response: Hotels.Something.Response)
}

class HotelsPresenter: HotelsPresentationLogic {
    
    weak var viewController: HotelsDisplayLogic?
    
    init(viewController: HotelsDisplayLogic) {
        
        self.viewController = viewController
    }
    
    // MARK: Do something
    
    func presentSomething(response: Hotels.Something.Response) {
        
        let viewModel = Hotels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
