# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hurb-challenge-alpha' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hurb-challenge-alpha
  pod 'SwiftLint'

  target 'hurb-challenge-alphaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hurb-challenge-alphaUITests' do
    # Pods for testing
  end

end
