# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

def shared_pods

 pod 'Alamofire'
 pod 'SwiftLint'
 pod 'lottie-ios'

end

target 'GPSurb' do
    shared_pods
end

target 'GPSurbTests' do
    shared_pods
end

target 'GPSurbUITests' do
   shared_pods
end

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      
    end
    
  end
  
end

