# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPSurb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  def shared_pods

   pod 'Alamofire'

  end

  target 'GPSurbTests' do
    shared_pods
  end

  target 'GPSurbUITests' do
   shared_pods
  end

end
