# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hotels' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hotels
  pod "EVReflection/Alamofire"
  pod 'SDWebImage'
  pod 'Cosmos'

  target 'HotelsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HotelsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
